### ISSUE TITLE
Training stages

### ISSUE THREAD

**Issue by stephengreen** [dingo-gw/dingo#34]
I am trying to think of a way to enable several stages of training, e.g., pre-training with a fixed PSD, and main training with variable PSD. One way I can think of is to specify in `train_settings.yaml` something like this:

```
# Usual stuff up here. This specifies the initial training settings ("stage 0")
noise: fixed_asd.txt
freeze_rb_layer: True

training_stage_1:
  start_epoch: 300  # Start second stage at 300 epochs
  noise: asd_dataset_O3.hdf5  # Only specify the settings that change from the initial settings.
  freeze_rb_layer: False
  scheduler:  ... # whatever
  
training_stage_2:
  start_epoch: 500  # If we wanted yet another stage
```

The code would then use the initial settings until epoch 300, at which point it rebuilds the transforms (and possibly the scheduler) based on the second-stage settings. It would obviously have to check for compatibility of the stages (e.g., so that we don't change the neural archictecture, etc.). We could also alter the settings mid-run, so long as we only change stages that begin *after* the current epoch.

What do you think? I'm also of course open to other suggestions.
